apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labs-ci-cd-argocd-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-gitops-argocd-server
subjects:
- kind: ServiceAccount
  name: argocd-argocd-server
  namespace: labs-ci-cd
