apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.3.1
  config:
    env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE  # dont deploy default argocd in openshift-gitops
      value: 'true'
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES # deploy cluster scoped argocd in these namespaces
      value: ${GITOPS_NAMESPACES}
